Repository QGEP/qgepqwat2ili, pull requests merged in 2024-10, with the labels that each got.

#163 2024 10 02 addcheck mandatory fk owner fk_operator fk_dataowner fk_provider fix missing references
  qgepqwat2ili/gui/__init__.py
  qgepqwat2ili/qgep/export.py
  qgepqwat2ili/qgepdss/export.py
  qgepqwat2ili/qgepsia405/export.py
  qgepqwat2ili/utils/ili2db.py
Labels: enhancement, Sustainability

#167 2024-10-11-fix-rollback_session
  qgepqwat2ili/gui/gui_import.py
Labels: fix

#168 Fix check_identifier_null()
  qgepqwat2ili/utils/ili2db.py
Labels: fix

#170 Log only when debug mode is active
  qgepqwat2ili/qgep/export.py
  qgepqwat2ili/qgepdss/export.py
  qgepqwat2ili/qgepsia405/export.py
  qgepqwat2ili/utils/ili2db.py
Labels: fix, Sustainability

#174 2024-10-24-fix-check_identifier_null-bad-state
  qgepqwat2ili/utils/ili2db.py
Labels: fix

#173 2024-10-18-testdata-add-correct-arc-sample
  qgepqwat2ili/data/test_data/case_c_import_all.xtf
  qgepqwat2ili/data/test_data/case_d_import_all_without_errors.xtf
Labels: fix

#171 Upgrade qgep used docker image
  qgepqwat2ili/gui/__init__.py
  qgepqwat2ili/qgep/export.py
  qgepqwat2ili/qgep/import_.py
  qgepqwat2ili/qgepdss/export.py
  qgepqwat2ili/qgepdss/import_.py
  qgepqwat2ili/qgepsia405/export.py
  qgepqwat2ili/qgepsia405/import_.py
  qgepqwat2ili/qwat/export.py
  qgepqwat2ili/utils/ili2db.py
  qgepqwat2ili/utils/various.py
Labels: fix, Sustainability
