Repository QGEP/qgepqwat2ili, pull requests merged in 2024-12, with the labels that each got.

#186 Fix try to access variable that is already out of scope
  qgepqwat2ili/utils/ili2db.py
Labels: fix

#183 Enable basket export for kek
  qgepqwat2ili/__init__.py
  qgepqwat2ili/config.py
  qgepqwat2ili/gui/__init__.py
  qgepqwat2ili/qgep/export.py
  qgepqwat2ili/tests/test_qgep.py
  qgepqwat2ili/utils/ili2db.py
  qgepqwat2ili/utils/qgep_export_utils.py
Labels: enhancement, ili2pg, fix, INTERLIS

#184 2024 12 11 fix ara bauwerk export 2nd attempt
  qgepqwat2ili/gui/__init__.py
  qgepqwat2ili/gui/gui_export.py
  qgepqwat2ili/qgep/export.py
  qgepqwat2ili/qgepdss/export.py
  qgepqwat2ili/qgepsia405/export.py
  qgepqwat2ili/utils/qgep_export_utils.py
Labels: enhancement, fix
